---

ci:
  skip:
  - pylint  # `local` hooks can't run on pre-commit.ci

repos:
- repo: https://github.com/asottile/add-trailing-comma.git
  rev: v0.7.1
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/Lucas-C/pre-commit-hooks.git
  rev: v1.1.1
  hooks:
  - id: remove-tabs

- repo: https://github.com/Lucas-C/pre-commit-hooks-markup.git
  rev: v1.0.0
  hooks:
  - id: rst-linter

- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v2.0.0
  hooks:
  # Side-effects:
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
    exclude: requirements.txt

  # Non-modifying checks:
  - id: name-tests-test
  - id: check-added-large-files
  - id: check-byte-order-marker
  - id: check-case-conflict
  # disabled due to pre-commit/pre-commit-hooks#159
  #- id: check-docstring-first
  - id: check-json
  - id: check-symlinks
  - id: check-yaml
  - id: detect-private-key

  # Heavy checks:
  - id: check-ast
  - id: debug-statements

- repo: https://github.com/PyCQA/flake8.git
  rev: 6.0.0
  hooks:
  - id: flake8
    alias: flake8-no-wps
    name: flake8 WPS-excluded
    additional_dependencies:
    # - darglint ~= 1.8.1
    - flake8-2020 ~= 1.7.0
    # - flake8-annotations ~= 2.9.1; python_version >= "3.7"
    # - flake8-annotations ~= 2.7.0; python_version < "3.7"
    - flake8-docstrings ~= 1.6.0
    - flake8-length ~= 0.3.0
    - flake8-logging-format ~= 0.7.5
    - flake8-pytest-style ~= 1.6.0
    # - flake8-spellcheck ~= 0.28.0; python_version >= "3.8"
    # - flake8-spellcheck ~= 0.26.0; python_version < "3.8"
    language_version: python3

# - repo: https://github.com/PyCQA/flake8.git
#   # NOTE: This is kept at v4 for until WPS starts supporting flake v5.
#   rev: 4.0.1  # enforce-version: 4.0.1
#   hooks:
#   - id: flake8
#     alias: flake8-only-wps
#     name: flake8 WPS-only
#     args:
#     - --select
#     - WPS
#     additional_dependencies:
#     - wemake-python-styleguide ~= 0.17.0
#     language_version: python3

- repo: local
  hooks:
  - id: pylint
    language: system
    name: PyLint
    files: \.py$
    entry: python -m pylint.__main__
    args:
    - --msg-template={path}:L {line:3d}:({symbol}) {msg} (C {column:2d}), ::{msg_id}
    - --output-format=colorized
    - --known-standard-library=contextvars
    - --min-similarity-lines=6
    - --good-names=logger

...
